[package]
name = "age_in_days"
version = "0.1.0"
authors = ["Thibault Mambour <thibault.mambour@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
time = "0.2.4"
